### ISSUE TITLE
一些小小的个人想法

### ISSUE THREAD

**Issue by yuano0** [mx-space/docs#139]
### Clear and concise description of the problem

用Kami也挺久了，就我使用的来说说，kami真的很好啊，而且一些维护的人也非常友善，有问必答，超级喜欢这个的。

想来说一下一些自己的想法。

1：个人理解，<近期技术输出-用文字记录生活> 是可以用来记录技术和生活输出的，

诉の动态是可以用来写一些生活中的一些小事情的，感觉诉会让我用的更习惯一点。

但是我在想诉的时候，说一些琐碎的小事等等，其实我是希望诉可以有些互动的，诉它没有评论功能，会让我稍微苦恼点。。

2：评论功能

感觉评论的表情好单调噢，是一些颜文字，或许会不会加一些emoji等等表情包能更好玩一些......

这只是我的一些想法，或许可以做一个点子，

### Suggested solution

评论和诉。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ttimochan** [comment]
文档的改进意见请发到这里，如果想提 Issue ，请看清楚地方 https://mx-space.js.org/guide/ 
 
感谢！
